version: '{build}'
branches:
  only:
  - dev
skip_tags: true
image: Visual Studio 2019
configuration: Release
init:
- cmd: >-
    @echo off

    for /f %%a in ('powershell -Command "Get-Date -format yy.MM.dd.HHmm"') do set BUILD_VERSION=%%a
environment:
  BUILD_VERSION: 0.0.0.0
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- cmd: '%APPVEYOR_BUILD_FOLDER%/Tools/build.bat'
test: off
deploy: off
on_success:
- cmd: '%APPVEYOR_BUILD_FOLDER%/Tools/deploy.bat'