version: '{build}'
branches:
  only:
  - dev
image: Visual Studio 2019
configuration: Release
init:
- cmd: >-
    @echo off

    for /f %%a in ('powershell -Command "Get-Date -format yy.MM.dd.HHmm"') do set BUILD_VERSION=%%a
environment:
  BUILD_VERSION: 0.0.0.0
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- cmd: >-
    @echo off

    echo Build Version: %BUILD_VERSION%

    dotnet clean --configuration Release

    dotnet restore --force

    dotnet build --configuration Release
test: off
deploy: off
on_success:
- cmd: >-
    dotnet publish -c Release -r win-x64 --self-contained true

    dotnet publish -c Release -r linux-x64 --self-contained true

    dotnet publish -c Release -r osx-x64 --self-contained true