version: '{build}'
branches:
  only:
  - dev
skip_tags: true
image: Visual Studio 2019
configuration: Release
environment:
  BUILD_VERSION: 0.0.0.0
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- cmd: >-
    CALL %APPVEYOR_BUILD_FOLDER%/Tools/init.bat

    CALL %APPVEYOR_BUILD_FOLDER%/Tools/sanity_check.bat

    CALL %APPVEYOR_BUILD_FOLDER%/Tools/build.bat
test: off
artifacts:
- path: publish/windows_$(BUILD_VERSION).exe
  name: windows
- path: publish/linux_portable_$(BUILD_VERSION).zip
  name: linux_portable
- path: publish/osx_portable_$(BUILD_VERSION).zip
  name: mac_portable
- path: publish/windows_portable_$(BUILD_VERSION).zip
  name: windows_portable
deploy:
- provider: GitHub
  tag: $(BUILD_VERSION)
  release: $(BUILD_VERSION)
  description: Automated release of v$(BUILD_VERSION).
  auth_token:
    secure: UgS7u6/QF29WDtX3jzm9xC64vZ52V8yGYWAvpMW+h+95ghtdOHalzcmyemVTg28H
  repository: waliarubal/Jaya
  artifact: publish/windows_$(BUILD_VERSION).exe,publish/linux_portable_$(BUILD_VERSION).zip,publish/osx_portable_$(BUILD_VERSION).zip,publish/windows_portable_$(BUILD_VERSION).zip
  prerelease: true
  on:
    branch: dev