version: '{build}'
branches:
  only:
  - dev
skip_tags: true
image: Visual Studio 2019
configuration: Release
environment:
  BUILD_VERSION: 0.0.0.0
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- cmd: >-
    CALL %APPVEYOR_BUILD_FOLDER%/Tools/init.bat

    CALL %APPVEYOR_BUILD_FOLDER%/Tools/sanity_check.bat

    CALL %APPVEYOR_BUILD_FOLDER%/Tools/build.bat
test: off
artifacts:
- path: publish/windows_$(BUILD_VERSION).exe
  name: windows
- path: publish/linux_portable_$(BUILD_VERSION).zip
  name: linux_portable
- path: publish/osx_portable_$(BUILD_VERSION).zip
  name: mac_portable
- path: publish/windows_portable_$(BUILD_VERSION).zip
  name: windows_portable
deploy: off