version: '{build}'
branches:
  only:
  - dev
skip_tags: true
image: Visual Studio 2019
configuration: Release
environment:
  BUILD_VERSION: 0.0.0.0
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- cmd: >-
    CALL %APPVEYOR_BUILD_FOLDER%/Tools/init.bat

    CALL %APPVEYOR_BUILD_FOLDER%/Tools/build.bat

    CALL %APPVEYOR_BUILD_FOLDER%/Tools/deploy.bat
test: off
artifacts:
- path: publish/WindowsInstaller.exe
  name: windows
- path: publish/linux_$(BUILD_VERSION).zip
  name: linux
- path: publish/osx_$(BUILD_VERSION).zip
  name: mac
deploy: off